#!/usr/bin/env python

import sys
from setuptools import setup, find_packages

if sys.version_info >= (3, 8):
    from importlib import metadata
else:
    from importlib_metadata import metadata

# This is the setup.py for a developmental version. The Officially tagged versions will have an overwritten 
# setup.py as generated by poetry https://pypi.org/project/poetry/
VERSION = 'dev'
DESCRIPTION = 'A python based toolkit to download and analyse data from the Ethoscope hardware system.'

with open("README.md", "r", encoding="utf-8") as fh:
    LONG_DESCRIPTION = fh.read()

setup(
        name = "ethoscopy", 
        version = VERSION,
        author = "Laurence Blackhurst",
        author_email = "l.blackhurst19@imperial.ac.uk",
        description = DESCRIPTION,
        long_description = LONG_DESCRIPTION,
        packages = find_packages('src'),
        package_dir = {'' : 'src'},
        install_requires=['pandas >= 1.4', 'numpy >= 1.22',],
        keywords=['python', 'ethomics', 'ethoscope', 'sleep'],
        classifiers= [
            "Development Status :: 3 - Alpha",
            "Intended Audience :: Education",
            "Programming Language :: Python :: 3",
            "Operating System :: Microsoft :: Windows",
            "Operating System :: POSIX",
            "Operating System :: MacOS :: MacOS X"
        ],
        python_requires = ">=3.8"
)
